package com.example.demo.service;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.UUID;

/**
 * Service layer for User operations in a Spring WebFlux application.
 * 
 * <p>This service provides business logic for user management operations.
 * It acts as an intermediary between the controller layer and the repository layer,
 * handling business rules, validation, and data transformation.</p>
 * 
 * <p>Key responsibilities:</p>
 * <ul>
 *   <li>Business logic enforcement</li>
 *   <li>Data validation and transformation</li>
 *   <li>Error handling and custom exceptions</li>
 *   <li>Coordination between multiple repositories if needed</li>
 * </ul>
 * 
 * @author Generated by GitHub Copilot
 * @version 1.0
 * @since 1.0
 */
@Service
public class UserService {
    
    private final UserRepository userRepository;
    
    /**
     * Constructor for dependency injection.
     * 
     * @param userRepository the user repository to be injected
     */
    @Autowired
    public UserService(UserRepository userRepository) {
        this.userRepository = userRepository;
    }
    
    /**
     * Creates a new user with auto-generated ID.
     * 
     * <p>This method generates a unique ID for the user and validates
     * that the email address is not already in use.</p>
     * 
     * @param firstName the user's first name, must not be null or empty
     * @param lastName the user's last name, must not be null or empty
     * @param email the user's email address, must not be null or empty
     * @return a {@link Mono} emitting the created user
     * @throws IllegalArgumentException if email already exists
     */
    public Mono<User> createUser(String firstName, String lastName, String email) {
        return userRepository.existsByEmail(email)
                .flatMap(exists -> {
                    if (Boolean.TRUE.equals(exists)) {
                        return Mono.error(new IllegalArgumentException("Email already exists: " + email));
                    }
                    String id = UUID.randomUUID().toString();
                    User newUser = new User(id, firstName, lastName, email);
                    return userRepository.save(newUser);
                });
    }
    
    /**
     * Retrieves a user by their unique identifier.
     * 
     * @param id the user ID to search for
     * @return a {@link Mono} emitting the user if found, or empty if not found
     */
    public Mono<User> getUserById(String id) {
        return userRepository.findById(id);
    }
    
    /**
     * Retrieves a user by their email address.
     * 
     * @param email the email address to search for
     * @return a {@link Mono} emitting the user if found, or empty if not found
     */
    public Mono<User> getUserByEmail(String email) {
        return userRepository.findByEmail(email);
    }
    
    /**
     * Retrieves all users from the repository.
     * 
     * @return a {@link Flux} emitting all users
     */
    public Flux<User> getAllUsers() {
        return userRepository.findAll();
    }
    
    /**
     * Searches for users by name (first name or last name containing the search term).
     * 
     * @param searchTerm the term to search for in user names
     * @return a {@link Flux} emitting matching users
     */
    public Flux<User> searchUsersByName(String searchTerm) {
        return userRepository.findByNameContaining(searchTerm);
    }
    
    /**
     * Updates an existing user's information.
     * 
     * <p>This method validates that the user exists and that the new email
     * (if different from current) is not already in use by another user.</p>
     * 
     * @param id the ID of the user to update
     * @param firstName the new first name
     * @param lastName the new last name
     * @param email the new email address
     * @return a {@link Mono} emitting the updated user
     * @throws IllegalArgumentException if user not found or email conflict
     */
    public Mono<User> updateUser(String id, String firstName, String lastName, String email) {
        return userRepository.findById(id)
                .switchIfEmpty(Mono.error(new IllegalArgumentException("User not found with id: " + id)))
                .flatMap(existingUser -> {
                    // If email is changing, check if new email is already in use
                    if (!email.equals(existingUser.getEmail())) {
                        return userRepository.existsByEmail(email)
                                .flatMap(emailExists -> {
                                    if (Boolean.TRUE.equals(emailExists)) {
                                        return Mono.error(new IllegalArgumentException("Email already exists: " + email));
                                    }
                                    User updatedUser = existingUser.withUpdatedInfo(firstName, lastName, email);
                                    return userRepository.save(updatedUser);
                                });
                    } else {
                        // Email is not changing, proceed with update
                        User updatedUser = existingUser.withUpdatedInfo(firstName, lastName, email);
                        return userRepository.save(updatedUser);
                    }
                });
    }
    
    /**
     * Deletes a user by their unique identifier.
     * 
     * @param id the ID of the user to delete
     * @return a {@link Mono} emitting {@code true} if user was deleted, {@code false} if not found
     */
    public Mono<Boolean> deleteUser(String id) {
        return userRepository.existsById(id)
                .flatMap(exists -> {
                    if (Boolean.TRUE.equals(exists)) {
                        return userRepository.deleteById(id).then(Mono.just(true));
                    } else {
                        return Mono.just(false);
                    }
                });
    }
    
    /**
     * Checks if a user exists with the given ID.
     * 
     * @param id the user ID to check
     * @return a {@link Mono} emitting {@code true} if user exists, {@code false} otherwise
     */
    public Mono<Boolean> userExists(String id) {
        return userRepository.existsById(id);
    }
    
    /**
     * Checks if a user exists with the given email address.
     * 
     * @param email the email address to check
     * @return a {@link Mono} emitting {@code true} if user exists, {@code false} otherwise
     */
    public Mono<Boolean> emailExists(String email) {
        return userRepository.existsByEmail(email);
    }
    
    /**
     * Gets the total count of users.
     * 
     * @return a {@link Mono} emitting the total number of users
     */
    public Mono<Long> getUserCount() {
        return userRepository.count();
    }
    
    /**
     * Deletes all users from the repository.
     * 
     * <p><strong>Caution:</strong> This method removes all user data.
     * Use with extreme care, typically only in test environments.</p>
     * 
     * @return a {@link Mono} that completes when all users are deleted
     */
    public Mono<Void> deleteAllUsers() {
        return userRepository.deleteAll();
    }
}
