package com.example.demo.config;

import com.example.demo.repository.impl.InMemoryUserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration class for application initialization.
 * 
 * <p>This configuration class provides beans and initialization logic
 * for the Spring Boot WebFlux application.</p>
 * 
 * @author Generated by GitHub Copilot
 * @version 1.0
 * @since 1.0
 */
@Configuration
public class ApplicationConfig {
    
    /**
     * CommandLineRunner bean to initialize sample data on application startup.
     * 
     * <p>This runner will populate the in-memory repository with sample users
     * for testing and demonstration purposes.</p>
     * 
     * @param userRepository the in-memory user repository
     * @return CommandLineRunner for data initialization
     */
    @Bean
    public CommandLineRunner initData(@Autowired InMemoryUserRepository userRepository) {
        return args -> userRepository.initializeSampleData().subscribe();
    }
}
